import request from './request';

export const register = (data) => request.post('/auth/register', data);
export const login = (data) => request.post('/auth/login', data);
export const logout = () => request.post('/auth/logout');
export const getProfile = () => request.get('/auth/profile');
export const getDashboard = () => request.get('/auth/dashboard');
export const updateProfile = (data) => request.put('/auth/profile', data);
export const updatePassword = (data) => request.put('/auth/password', data);
export const uploadAvatar = (data) => request.post('/auth/avatar', data);
export const deleteAccount = (data) => request.delete('/auth/account', { data });
export const getSecurityQuestions = () => request.get('/auth/security-questions');
export const getUserSecurityQuestion = (username) => request.get('/auth/security-question', { params: { username } });
export const resetPassword = (data) => request.post('/auth/reset-password', data);
export const getMyPosts = (params) => request.get('/auth/my-posts', { params });
export const getMyComments = (params) => request.get('/auth/my-comments', { params });
export const getPosts = (params) => request.get('/posts', { params });
export const createPost = (data) => request.post('/posts', data);
export const updatePost = (id, data) => request.put(`/posts/${id}`, data);
export const deletePost = (id) => request.delete(`/posts/${id}`);
export const getPostDetail = (id, params) => request.get(`/posts/${id}`, { params });
export const toggleLike = (id) => request.post(`/posts/${id}/like`);
export const toggleFavorite = (id) => request.post(`/posts/${id}/favorite`);
export const createComment = (id, data) => request.post(`/posts/${id}/comment`, data);
export const incrementViews = (id) => request.post(`/posts/${id}/views`);
export const getRecommendedPosts = (params) => request.get('/posts/recommended', { params });
export const deleteComment = (postId, commentId) => request.delete(`/posts/${postId}/comment/${commentId}`);
export const getFollowing = (params) => request.get('/follows/following', { params });
export const getFans = (params) => request.get('/follows/fans', { params });
export const toggleFollow = (id) => request.post(`/follows/${id}/toggle`);
export const getConversations = () => request.get('/messages/conversations');
export const getPrivateHistory = (id) => request.get(`/messages/private/${id}`);
export const sendPrivate = (id, data) => request.post(`/messages/private/${id}`, data);
export const getGroupHistory = () => request.get('/messages/group');
export const sendGroup = (data) => request.post('/messages/group', data);
